/*
Copyright by bingerambo@gmail.com

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	inspur_com_v1 "github.com/bingerambo/crd-code-generation/pkg/apis/inspur.com/v1"
	versioned "github.com/bingerambo/crd-code-generation/pkg/nodecache_client/clientset/versioned"
	internalinterfaces "github.com/bingerambo/crd-code-generation/pkg/nodecache_client/informers/externalversions/internalinterfaces"
	v1 "github.com/bingerambo/crd-code-generation/pkg/nodecache_client/listers/inspur/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// NodeCacheInformer provides access to a shared informer and lister for
// NodeCaches.
type NodeCacheInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.NodeCacheLister
}

type nodeCacheInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewNodeCacheInformer constructs a new informer for NodeCache type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNodeCacheInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.InspurV1().NodeCaches(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.InspurV1().NodeCaches(namespace).Watch(options)
			},
		},
		&inspur_com_v1.NodeCache{},
		resyncPeriod,
		indexers,
	)
}

func defaultNodeCacheInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewNodeCacheInformer(client, meta_v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *nodeCacheInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&inspur_com_v1.NodeCache{}, defaultNodeCacheInformer)
}

func (f *nodeCacheInformer) Lister() v1.NodeCacheLister {
	return v1.NewNodeCacheLister(f.Informer().GetIndexer())
}
