apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodecaches.inspur.com
spec:
  group: inspur.com
  names:
    kind: NodeCache
    listKind: NodeCacheList
    plural: nodecaches
  scope: Cluster
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            datasets:
              type: string
            freesize:
              format: int64
              type: integer
            allocatablesize:
              format: int64
              type: integer
          type: object
        status:
          properties:
            unknown:
              format: int32
              type: integer
            pending:
              format: int32
              type: integer
            running:
              format: int32
              type: integer
          type: object
      type: object
